/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kdl.minecraft.desktop.menu;

import java.net.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import java.util.Arrays;
import kdl.minecraft.recursos.Sonido;
import kdl.minecraft.basedatos.*;
import kdl.minecraft.comunicacion.Jugador;
import kdl.minecraft.comunicacion.PaqueteOperacion;
import kdl.minecraft.comunicacion.PaqueteOperacion.Operacion;
import kdl.minecraft.comunicacion.PaqueteOperacion.ResultadoOperacion;
import kdl.minecraft.comunicacion.Partida;

/**
 *
 * @author luisb
 */
public final class FrmPrincipal extends javax.swing.JFrame implements Runnable
{

    public static final int ALTURA_VENTANA = 500;
    public static final int ANCHURA_VENTANA = 855;

    private static DBUsuario usuarioLogueado;
    private static int personajeSeleccionado;

    /**
     * Crea la ventana principal del juego.
     */
    public FrmPrincipal()
    {
        super("Minecraft: La Batalla del Ender");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        btnComenzarPartida.setVisible(false);

        personajeSeleccionado = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jlpPrincipal = new javax.swing.JLayeredPane();
        panelBienvenida = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnAcerca = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        fondoBienvenida = new javax.swing.JLabel();
        panelIniciar = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        txtUsuarioIniciar = new javax.swing.JTextField();
        lblPass2 = new javax.swing.JLabel();
        txtPassIniciar = new javax.swing.JPasswordField();
        btnAceptarInicio = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        fondoIniciar = new javax.swing.JLabel();
        panelRegistrarse = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblPass1 = new javax.swing.JLabel();
        txtPassConfirmar = new javax.swing.JPasswordField();
        btnAceptarRegistro = new javax.swing.JButton();
        btnVolver1 = new javax.swing.JButton();
        fondoRegistrarse = new javax.swing.JLabel();
        panelAyuda = new javax.swing.JPanel();
        btnVolver2 = new javax.swing.JButton();
        fondoAyuda = new javax.swing.JLabel();
        panelAcercaDe = new javax.swing.JPanel();
        btnVolver3 = new javax.swing.JButton();
        btnCambiarServidor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        logo2 = new javax.swing.JLabel();
        fondoAcerca = new javax.swing.JLabel();
        panelPartida = new javax.swing.JPanel();
        lblFlechaIzquierda = new javax.swing.JLabel();
        lblFlechaDerecha = new javax.swing.JLabel();
        lblPersonaje = new javax.swing.JLabel();
        logo3 = new javax.swing.JLabel();
        lblNickname = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jlCrear = new javax.swing.JLayeredPane();
        jpCrear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombrePartida = new javax.swing.JTextField();
        txtDescPartida = new javax.swing.JTextField();
        spinCantJugadores = new javax.swing.JSpinner();
        btnCrearPartida = new javax.swing.JButton();
        jlUnirse = new javax.swing.JLayeredPane();
        jpUnirse = new javax.swing.JPanel();
        btnComenzarPartida = new javax.swing.JButton();
        btnVolver4 = new javax.swing.JButton();
        fondoAcerca1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        setMinimumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        setPreferredSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));

        jlpPrincipal.setMaximumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        jlpPrincipal.setMinimumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        jlpPrincipal.setPreferredSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        jlpPrincipal.setLayout(new java.awt.CardLayout());

        panelBienvenida.setMaximumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelBienvenida.setMinimumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelBienvenida.setPreferredSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelBienvenida.setLayout(null);

        btnIniciarSesion.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnIniciarSesion.setText("INICIAR SESIÓN");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        panelBienvenida.add(btnIniciarSesion);
        btnIniciarSesion.setBounds(10, 420, 170, 40);

        btnRegistrar.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnRegistrar.setText("REGISTRARSE");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarActionPerformed(evt);
            }
        });
        panelBienvenida.add(btnRegistrar);
        btnRegistrar.setBounds(190, 420, 170, 40);

        btnEstadisticas.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnEstadisticas.setText("ESTADÍSTICAS");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEstadisticasActionPerformed(evt);
            }
        });
        panelBienvenida.add(btnEstadisticas);
        btnEstadisticas.setBounds(370, 420, 170, 40);

        btnAcerca.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnAcerca.setText("ACERCA DE");
        btnAcerca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAcercaActionPerformed(evt);
            }
        });
        panelBienvenida.add(btnAcerca);
        btnAcerca.setBounds(710, 420, 130, 40);

        btnAyuda.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnAyuda.setText("AYUDA");
        btnAyuda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAyudaActionPerformed(evt);
            }
        });
        panelBienvenida.add(btnAyuda);
        btnAyuda.setBounds(710, 10, 130, 40);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        logo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logo.setMaximumSize(new java.awt.Dimension(200, 140));
        panelBienvenida.add(logo);
        logo.setBounds(20, 10, 310, 140);

        fondoBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/principal.jpg"))); // NOI18N
        panelBienvenida.add(fondoBienvenida);
        fondoBienvenida.setBounds(0, 0, 850, 480);

        jlpPrincipal.add(panelBienvenida, "card2");

        panelIniciar.setMaximumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelIniciar.setMinimumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelIniciar.setPreferredSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelIniciar.setLayout(null);

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        logo1.setMaximumSize(new java.awt.Dimension(200, 140));
        panelIniciar.add(logo1);
        logo1.setBounds(260, 30, 320, 150);

        lblUsuario1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario1.setLabelFor(txtCorreo);
        lblUsuario1.setText("Usuario:");
        panelIniciar.add(lblUsuario1);
        lblUsuario1.setBounds(260, 190, 320, 30);

        txtUsuarioIniciar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        panelIniciar.add(txtUsuarioIniciar);
        txtUsuarioIniciar.setBounds(260, 220, 320, 40);

        lblPass2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblPass2.setForeground(new java.awt.Color(255, 255, 255));
        lblPass2.setLabelFor(txtCorreo);
        lblPass2.setText("Contraseña:");
        panelIniciar.add(lblPass2);
        lblPass2.setBounds(260, 300, 320, 30);

        txtPassIniciar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        panelIniciar.add(txtPassIniciar);
        txtPassIniciar.setBounds(260, 330, 320, 40);

        btnAceptarInicio.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnAceptarInicio.setText("INICIAR");
        btnAceptarInicio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarInicioActionPerformed(evt);
            }
        });
        panelIniciar.add(btnAceptarInicio);
        btnAceptarInicio.setBounds(670, 420, 170, 40);

        btnVolver.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });
        panelIniciar.add(btnVolver);
        btnVolver.setBounds(10, 420, 170, 40);

        fondoIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/tierra.png"))); // NOI18N
        panelIniciar.add(fondoIniciar);
        fondoIniciar.setBounds(0, 0, 850, 480);

        jlpPrincipal.add(panelIniciar, "card3");

        panelRegistrarse.setMaximumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelRegistrarse.setMinimumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelRegistrarse.setPreferredSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelRegistrarse.setLayout(null);

        lblCorreo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setLabelFor(txtCorreo);
        lblCorreo.setText("Correo electrónico:");
        panelRegistrarse.add(lblCorreo);
        lblCorreo.setBounds(260, 50, 320, 30);

        txtCorreo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        panelRegistrarse.add(txtCorreo);
        txtCorreo.setBounds(260, 80, 320, 40);

        lblUsuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setLabelFor(txtCorreo);
        lblUsuario.setText("Usuario:");
        panelRegistrarse.add(lblUsuario);
        lblUsuario.setBounds(260, 150, 320, 30);

        txtUsuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        panelRegistrarse.add(txtUsuario);
        txtUsuario.setBounds(260, 180, 320, 40);

        lblPass.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setLabelFor(txtCorreo);
        lblPass.setText("Contraseña:");
        panelRegistrarse.add(lblPass);
        lblPass.setBounds(260, 240, 320, 30);

        txtPass.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        panelRegistrarse.add(txtPass);
        txtPass.setBounds(260, 270, 320, 40);

        lblPass1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblPass1.setForeground(new java.awt.Color(255, 255, 255));
        lblPass1.setLabelFor(txtCorreo);
        lblPass1.setText("Confirmar contraseña:");
        panelRegistrarse.add(lblPass1);
        lblPass1.setBounds(260, 340, 320, 30);

        txtPassConfirmar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        panelRegistrarse.add(txtPassConfirmar);
        txtPassConfirmar.setBounds(260, 370, 320, 40);

        btnAceptarRegistro.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnAceptarRegistro.setText("REGISTRARSE");
        btnAceptarRegistro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarRegistroActionPerformed(evt);
            }
        });
        panelRegistrarse.add(btnAceptarRegistro);
        btnAceptarRegistro.setBounds(670, 420, 170, 40);

        btnVolver1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnVolver1.setText("VOLVER");
        btnVolver1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });
        panelRegistrarse.add(btnVolver1);
        btnVolver1.setBounds(10, 420, 170, 40);

        fondoRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/tierra.png"))); // NOI18N
        panelRegistrarse.add(fondoRegistrarse);
        fondoRegistrarse.setBounds(0, 0, 850, 480);

        jlpPrincipal.add(panelRegistrarse, "card3");

        panelAyuda.setMaximumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelAyuda.setMinimumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelAyuda.setPreferredSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelAyuda.setLayout(null);

        btnVolver2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnVolver2.setText("VOLVER");
        btnVolver2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });
        panelAyuda.add(btnVolver2);
        btnVolver2.setBounds(10, 420, 170, 40);

        fondoAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/tierra.png"))); // NOI18N
        panelAyuda.add(fondoAyuda);
        fondoAyuda.setBounds(0, 0, 850, 480);

        jlpPrincipal.add(panelAyuda, "card3");

        panelAcercaDe.setMaximumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelAcercaDe.setMinimumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelAcercaDe.setPreferredSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelAcercaDe.setLayout(null);

        btnVolver3.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnVolver3.setText("VOLVER");
        btnVolver3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });
        panelAcercaDe.add(btnVolver3);
        btnVolver3.setBounds(10, 420, 170, 40);

        btnCambiarServidor.setText("Servidor");
        btnCambiarServidor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCambiarServidorActionPerformed(evt);
            }
        });
        panelAcercaDe.add(btnCambiarServidor);
        btnCambiarServidor.setBounds(570, 430, 80, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Aquí va la info");
        jScrollPane1.setViewportView(jTextArea1);

        panelAcercaDe.add(jScrollPane1);
        jScrollPane1.setBounds(200, 230, 460, 230);

        logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kdlteam.png"))); // NOI18N
        logo2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelAcercaDe.add(logo2);
        logo2.setBounds(250, 30, 340, 190);

        fondoAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/tierra.png"))); // NOI18N
        panelAcercaDe.add(fondoAcerca);
        fondoAcerca.setBounds(0, 0, 850, 480);

        jlpPrincipal.add(panelAcercaDe, "card3");

        panelPartida.setMaximumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelPartida.setMinimumSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelPartida.setPreferredSize(new java.awt.Dimension(ANCHURA_VENTANA, ALTURA_VENTANA));
        panelPartida.setLayout(null);

        lblFlechaIzquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlechaIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprites/flechaDer.png"))); // NOI18N
        lblFlechaIzquierda.setToolTipText("");
        lblFlechaIzquierda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFlechaIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFlechaIzquierda.setMaximumSize(new java.awt.Dimension(190, 150));
        lblFlechaIzquierda.setMinimumSize(new java.awt.Dimension(190, 150));
        lblFlechaIzquierda.setPreferredSize(new java.awt.Dimension(190, 150));
        lblFlechaIzquierda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblFlechaIzquierdaMouseClicked(evt);
            }
        });
        panelPartida.add(lblFlechaIzquierda);
        lblFlechaIzquierda.setBounds(750, 280, 70, 70);

        lblFlechaDerecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlechaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprites/flechaIzq.png"))); // NOI18N
        lblFlechaDerecha.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFlechaDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFlechaDerecha.setMaximumSize(new java.awt.Dimension(190, 150));
        lblFlechaDerecha.setMinimumSize(new java.awt.Dimension(190, 150));
        lblFlechaDerecha.setPreferredSize(new java.awt.Dimension(190, 150));
        lblFlechaDerecha.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblFlechaDerechaMouseClicked(evt);
            }
        });
        panelPartida.add(lblFlechaDerecha);
        lblFlechaDerecha.setBounds(520, 280, 80, 70);

        lblPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprites/personaje/0.png"))); // NOI18N
        lblPersonaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblPersonaje.setMaximumSize(new java.awt.Dimension(190, 150));
        lblPersonaje.setMinimumSize(new java.awt.Dimension(190, 150));
        lblPersonaje.setPreferredSize(new java.awt.Dimension(190, 150));
        panelPartida.add(lblPersonaje);
        lblPersonaje.setBounds(620, 250, 110, 150);

        logo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        logo3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelPartida.add(logo3);
        logo3.setBounds(500, 40, 340, 150);

        lblNickname.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblNickname.setForeground(new java.awt.Color(255, 255, 255));
        lblNickname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNickname.setText("Bienvenido, barreto.exe");
        lblNickname.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelPartida.add(lblNickname);
        lblNickname.setBounds(500, 210, 340, 30);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Nombre de Partida");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("Descripción de la Partida");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("Límite de Jugadores");

        txtNombrePartida.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        txtDescPartida.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        spinCantJugadores.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        spinCantJugadores.setModel(new javax.swing.SpinnerNumberModel(2, 2, 6, 1));

        btnCrearPartida.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnCrearPartida.setText("CREAR");
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCrearPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCrearLayout = new javax.swing.GroupLayout(jpCrear);
        jpCrear.setLayout(jpCrearLayout);
        jpCrearLayout.setHorizontalGroup(
            jpCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCrearLayout.createSequentialGroup()
                        .addGroup(jpCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jpCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spinCantJugadores, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 192, Short.MAX_VALUE))
                    .addComponent(txtDescPartida, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCrearLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombrePartida, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18))
        );
        jpCrearLayout.setVerticalGroup(
            jpCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombrePartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinCantJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jlCrear.add(jpCrear);
        jpCrear.setBounds(0, 0, 470, 330);

        jTabbedPane1.addTab("Crear Partida", jlCrear);

        jlUnirse.add(jpUnirse);
        jpUnirse.setBounds(0, 0, 470, 330);

        jTabbedPane1.addTab("Unirse a Partida", jlUnirse);

        panelPartida.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 40, 470, 360);

        btnComenzarPartida.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnComenzarPartida.setText("COMENZAR");
        btnComenzarPartida.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnComenzarPartidaActionPerformed(evt);
            }
        });
        panelPartida.add(btnComenzarPartida);
        btnComenzarPartida.setBounds(670, 420, 170, 40);

        btnVolver4.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnVolver4.setText("VOLVER");
        btnVolver4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });
        panelPartida.add(btnVolver4);
        btnVolver4.setBounds(10, 420, 170, 40);

        fondoAcerca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/tierra.png"))); // NOI18N
        panelPartida.add(fondoAcerca1);
        fondoAcerca1.setBounds(0, 0, 850, 480);

        jlpPrincipal.add(panelPartida, "card3");

        getContentPane().add(jlpPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Sonido.Click();
        mostrarPanel(panelAyuda);
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        Sonido.Click();
        mostrarPanel(panelAcercaDe);
    }//GEN-LAST:event_btnAcercaActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        Sonido.Click();
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Sonido.Click();
        mostrarPanel(panelRegistrarse);
        txtCorreo.requestFocus();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        Sonido.Click();
        mostrarPanel(panelIniciar);
        txtUsuarioIniciar.requestFocus();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVolverActionPerformed
    {//GEN-HEADEREND:event_btnVolverActionPerformed
        Sonido.Click();
        mostrarPanel(panelBienvenida);
        limpiarTextBoxes();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAceptarRegistroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarRegistroActionPerformed
    {//GEN-HEADEREND:event_btnAceptarRegistroActionPerformed
        Sonido.Click();

        String usuario = txtUsuario.getText();
        String correo = txtCorreo.getText();
        char[] pass = txtPass.getPassword();

        //Verificar que las contraseñas sean iguales y que no estén vacías
        if (!Arrays.equals(txtPass.getPassword(), txtPassConfirmar.getPassword()))
        {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
        } //Verificar que no haya campos vacíoss
        else if ("".equals(correo) || "".equals(usuario) || pass.length == 0)
        {
            JOptionPane.showMessageDialog(null, "Hay campos vacíos.");
        } else
        {
            //Crear instancia de usuario para enviarla al servidor
            DBUsuario usuarioObj = new DBUsuario(correo, usuario, txtPass.getText());
            PaqueteOperacion paquete = new PaqueteOperacion(Operacion.REGISTRAR, usuarioObj);
            
            try
            {
                //Enviar solicitud al server
                Socket socket = new Socket(DBUsuario.BASE_DATOS, 27015);
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                out.writeObject(paquete);
                socket.close();

                btnAceptarRegistro.setEnabled(false);
                btnVolver1.setEnabled(false);
            } catch (UnknownHostException ex)
            {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(null, "Host desconocido.", "Error", JOptionPane.ERROR_MESSAGE, null);
            } catch (IOException ex)
            {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(null, "No hubo conexión con el servidor.", "Error", JOptionPane.ERROR_MESSAGE, null);
            }
        }
    }//GEN-LAST:event_btnAceptarRegistroActionPerformed

    private void btnAceptarInicioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarInicioActionPerformed
    {//GEN-HEADEREND:event_btnAceptarInicioActionPerformed
        Sonido.Click();

        String usuario = txtUsuarioIniciar.getText();
        String pass = txtPassIniciar.getText();

        if ("".equals(usuario) || "".equals(pass))
        {
            JOptionPane.showMessageDialog(null, "Hay campos vacíos.");
        } else
        {
            //Crear instancia de usuario para enviarla al servidor
            DBUsuario usuarioObj = new DBUsuario(null, usuario, pass);
            PaqueteOperacion paquete = new PaqueteOperacion(Operacion.INICIAR_SESION, usuarioObj);
            
            usuarioLogueado = usuarioObj;

            try
            {
                //Enviar solicitud al server
                Socket socket = new Socket(DBUsuario.BASE_DATOS, 27015);
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                out.writeObject(paquete);
                socket.close();

                btnAceptarInicio.setEnabled(false);
                btnVolver.setEnabled(false);

            } catch (UnknownHostException ex)
            {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(null, "Host desconocido.", "Error", JOptionPane.ERROR_MESSAGE, null);
            } catch (IOException ex)
            {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(null, "No hubo conexión con el servidor.", "Error", JOptionPane.ERROR_MESSAGE, null);
            }
        }
    }//GEN-LAST:event_btnAceptarInicioActionPerformed

    private void btnCambiarServidorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCambiarServidorActionPerformed
    {//GEN-HEADEREND:event_btnCambiarServidorActionPerformed
        Sonido.Click();
        //Cambiar IP de la base de datos
        DBUsuario.BASE_DATOS = JOptionPane.showInputDialog(null, "Ingrese IP del servidor", DBUsuario.BASE_DATOS);
    }//GEN-LAST:event_btnCambiarServidorActionPerformed

    private void lblFlechaDerechaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFlechaDerechaMouseClicked
    {//GEN-HEADEREND:event_lblFlechaDerechaMouseClicked
        Sonido.Click();
        personajeSeleccionado--;
        elegirImagenPersonaje();
    }//GEN-LAST:event_lblFlechaDerechaMouseClicked

    private void lblFlechaIzquierdaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFlechaIzquierdaMouseClicked
    {//GEN-HEADEREND:event_lblFlechaIzquierdaMouseClicked
        Sonido.Click();
        personajeSeleccionado++;
        elegirImagenPersonaje();
    }//GEN-LAST:event_lblFlechaIzquierdaMouseClicked

    private void btnComenzarPartidaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnComenzarPartidaActionPerformed
    {//GEN-HEADEREND:event_btnComenzarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComenzarPartidaActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCrearPartidaActionPerformed
    {//GEN-HEADEREND:event_btnCrearPartidaActionPerformed
        Sonido.Click();
        String nombrePartida = txtNombrePartida.getText();
        String descripcionPartida = txtDescPartida.getText();
        int cantJugadores = (int) spinCantJugadores.getValue();

        if (nombrePartida.equals(""))
        {
            JOptionPane.showConfirmDialog(null, "El nombre de la partida no puede estar en blanco.");
            return;
        }

        Jugador creador = new Jugador(usuarioLogueado.getUsuario(), personajeSeleccionado);
        Partida partida = new Partida(nombrePartida, descripcionPartida, creador, cantJugadores);

        PaqueteOperacion paquete = new PaqueteOperacion(Operacion.CREAR_PARTIDA, partida);
        
        try
        {
            //Enviar solicitud al server
            Socket socket = new Socket(DBUsuario.BASE_DATOS, 27015);
            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
            out.writeObject(paquete);
            socket.close();
            
            btnCrearPartida.setEnabled(false);
        } 
        catch (UnknownHostException ex)
        {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Host desconocido.", "Error", JOptionPane.ERROR_MESSAGE, null);
        } catch (IOException ex)
        {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(null, "No hubo conexión con el servidor.", "Error", JOptionPane.ERROR_MESSAGE, null);
        }
        
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void elegirImagenPersonaje()
    {
        personajeSeleccionado = personajeSeleccionado % 6;

        if (personajeSeleccionado < 0)
        {
            personajeSeleccionado = personajeSeleccionado * -1 + 4;
        }

        lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprites/personaje/" + personajeSeleccionado + ".png")));
    }

    @Override
    public void run()
    {
        System.out.println("Esperando...");

        try
        {
            //Esperar posibles respuestas del servidor
            ServerSocket recibir = new ServerSocket(27016);
            while (true)
            {
                Socket socket = recibir.accept();
                ObjectInputStream paqueteRecibido = new ObjectInputStream(socket.getInputStream());
                ResultadoOperacion resultado = (ResultadoOperacion) paqueteRecibido.readObject();

                //Habilitar botones de nuevo
                new Thread(new Runnable()
                {
                    @Override
                    public void run()
                    {
                        btnAceptarRegistro.setEnabled(true);
                        btnVolver1.setEnabled(true);

                        btnAceptarInicio.setEnabled(true);
                        btnVolver.setEnabled(true);
                    }
                }).start();

                if (resultado == ResultadoOperacion.ERROR)
                {
                    JOptionPane.showMessageDialog(null, "Hubo un error en la operación.");
                }
                //Resultados de registro
                else if (resultado == ResultadoOperacion.CORREO_NO_DISPONIBLE)
                {
                    JOptionPane.showMessageDialog(null, "Correo no disponible.");
                }
                else if (resultado == ResultadoOperacion.USUARIO_NO_DISPONIBLE)
                {
                    JOptionPane.showMessageDialog(null, "Usuario no disponible.");
                }
                else if (resultado == ResultadoOperacion.USUARIO_REGISTRADO)
                {
                    JOptionPane.showMessageDialog(null, "¡Usuario registrado exitosamente!");
                    btnVolver.doClick();
                }
                //Resultados de inicio de sesión                
                else if (resultado == ResultadoOperacion.CREDENCIAL_INVALIDA)
                {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
                } 
                else if (resultado == ResultadoOperacion.SESION_VALIDA)
                {
                    mostrarPanel(panelPartida);
                    limpiarTextBoxes();
                    lblNickname.setText("Bienvenido, " + usuarioLogueado.getUsuario());
                }
            }
        } catch (IOException | ClassNotFoundException ex)
        {
            System.out.println(ex.getMessage());
        }

    }

    /**
     * Muestra el panel correspondiente en la ventana principal
     *
     * @param panel
     */
    private void mostrarPanel(JPanel panel)
    {
        //Colocar panel de bienvenida
        jlpPrincipal.removeAll();
        jlpPrincipal.add(panel);
        jlpPrincipal.revalidate();
    }

    /**
     * Limpia los campos de texto del menú.
     */
    private void limpiarTextBoxes()
    {
        this.txtCorreo.setText("");
        this.txtPass.setText("");
        this.txtPassConfirmar.setText("");
        this.txtPassIniciar.setText("");
        this.txtUsuario.setText("");
        this.txtUsuarioIniciar.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarInicio;
    private javax.swing.JButton btnAceptarRegistro;
    private javax.swing.JButton btnAcerca;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCambiarServidor;
    private javax.swing.JButton btnComenzarPartida;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JButton btnVolver3;
    private javax.swing.JButton btnVolver4;
    private javax.swing.JLabel fondoAcerca;
    private javax.swing.JLabel fondoAcerca1;
    private javax.swing.JLabel fondoAyuda;
    private javax.swing.JLabel fondoBienvenida;
    private javax.swing.JLabel fondoIniciar;
    private javax.swing.JLabel fondoRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLayeredPane jlCrear;
    private javax.swing.JLayeredPane jlUnirse;
    private javax.swing.JLayeredPane jlpPrincipal;
    private javax.swing.JPanel jpCrear;
    private javax.swing.JPanel jpUnirse;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFlechaDerecha;
    private javax.swing.JLabel lblFlechaIzquierda;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel logo3;
    private javax.swing.JPanel panelAcercaDe;
    private javax.swing.JPanel panelAyuda;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelIniciar;
    private javax.swing.JPanel panelPartida;
    private javax.swing.JPanel panelRegistrarse;
    private javax.swing.JSpinner spinCantJugadores;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDescPartida;
    private javax.swing.JTextField txtNombrePartida;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassConfirmar;
    private javax.swing.JPasswordField txtPassIniciar;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioIniciar;
    // End of variables declaration//GEN-END:variables

}
